### PR TITLE
Swift package

### PR DESCRIPTION
**Pull request by fousa**
I added the Package.swift configuration file in order to work with the new Swift Package Manager.

I only had to do one change in the code and that was to remove the `var` keyword in the `indentation` function declaration. All tests kept on running, so this shouldn't be a problem.

### CODE REVIEW

**Comment by tadija** [comment]
Thanks, var parameter was fixed in another PR, so I've just added Package.swift. This PR can be closed now.

**Comment by franklinyu** [comment]
Does this package work with Swift 3? If not, then what's the point of supporting Swift Package Manager?

**Comment by tadija** [comment]
Hi @franklinyu, good point.

**Comment by franklinyu** [comment]
@tadija I have a version working in Swift 3, but it is not compatible with Swift 2 any more, so we need two branches. Unfortunately, Swift Package Manager recognize versions *only* by tags, so we either

* rename tag `3.0.0` to `3.0.0-swift2` or something similar, and leave the `3.0.0` for Swift 3, or
* create a separate repository (possibly a [fork](/franklinyu/AEXML)) where the tag `3.0.0` is on branch `swift-3`.

The second seems better (though still not best). Any idea?

**Comment by tadija** [comment]
@franklinyu, to be honest, my plan was just to make the switch when swift 3.0 comes out of beta, until then we could have updated version on develop branch in case anyone needs it sooner.

**Comment by franklinyu** [comment]
@tadija, I might have misunderstood your meaning: did you mean that we are migrating *to* Swift 3, without keeping compatibility to Swift 2?

I thought we are keeping support to both Swift 2 and Swift 3, but the migration tool provided by Apple is really great; it is estimated to take less than a week for a small project to migrate with the help of compiler hint from Xcode. This changed my mind; now I think you might have meant to directly upgrade to Swift 3 without looking back?

P.S. Swift 3.0 beta is released with Xcode 8.0 beta.

**Pull request closed without merging**
