### PR TITLE
Updated project settings and podspec targets to use SWIFT_VERSION 3

### PR DESCRIPTION
**Pull request by vicng**
This fixes the problem where Xcode pops a warning that it needs to convert the project source into Swift 3, since it isn't sure that the code's been converted already.

### CODE REVIEW

**Comment by moh0sw** [comment]
Hi @vicng 
where can I edit the SWIFT_VERSION manually on the pod I've installed on my project?
because I think @tadija is not here to merge your pull request to the project
Thanks!

**Comment by vicng** [comment]
In your workspace, open the AEXML pod target and go to Build Settings. Find "Use Legacy Swift Language Version" and change it to "No" (you end up getting that annoying dialog because it's set to "Unspecified").

**Comment by vicng** [comment]
@tadija It'd be great if you could merge this! Every time I update my pods, I'll get the annoying pop up saying that AEXML needs to convert to the latest Swift syntax (even though it already is), and I need to manually fix the Build Settings every time.

**Comment by moh0sw** [comment]
Finally 😭👍

**Comment by tadija** [comment]
Thanks for the #PR @vicng, it's merged now in 4.0.1. Weird thing is that I never had these problems in my Xcode (8A218a), even before merging that.

**Comment by vicng** [comment]
Thanks! To be honest, I think there's some weird caching bug that's going on with Xcode 8.

**Pull request merged**
